export const data = [
  {
    type: "Recommended ",
    heading: "World Championship Package",
    actualPrice: "£200.50",
    price: "£150",
    get: [
      "Birthday Medals for All",
      "Glossy Party Certificates",
      "Great Basketball Level 2/3 Coash",
      "Birthday Present and Card",
      "All Equipment Including Basketball Hoops",
      "1.5 to 3 Hours of Backetball fun",
    ],
    size: 20,
  },
  {
    type: "Most Popular",
    heading: "NBA Championship Package",
    actualPrice: "£250.50",
    price: "£200",
    get: [
      "Birthday Child Trophy",
      "Real Medals for All",
      "Glossy Party Certificates",
      "Great Basketball Level 2/3 Coach",
      "Special Party Invitations",
      "Birthday Present and Card",
      "Goodie bags for all attendees",
      "All Equipment Including  Basketball hoops",
      "1.5 to 3 Hours of Basketball fun",
    ],
    size: 10,
  },
  {
    type: "Best Value ",
    heading: "English (BBL) Championship Package",
    actualPrice: "£150.50",
    price: "£100",
    get: [
      "Glossy Party Certificates",
      "Great Basketball Level 2/3 Coash",
      "Birthday Present and Card",
      "All Equipment Including Basketball Hoops",
      "1.5 to 3 Hours of Basketball fun",
    ],
    size: 20,
  },
];
